version: "3.1"

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: ProjectC
      MONGO_USERNAME: admin
      MONGO_PASSWORD: secret
    volumes:
      - ./data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
  cache:
    image: redis:alpine
    command: ['--requirepass "secret"']
